name = "caseeno"
compatibility_date = "2024-08-01"

# Cloudflare Pages output directory (built frontend)
pages_build_output_dir = "app/dist"

[vars]
# Add your environment variables here, e.g. API keys
# EXAMPLE_API_KEY = ""
